---
- name: Check if stap module is loaded
  become: true
  become_method: sudo
  shell: "lsmod | grep CVE_2016_5195"
  changed_when: False
  ignore_errors: True
  register: stap_loaded

- name: Copy the stap definition
  become: true
  become_method: sudo
  copy:
    src: CVE-2016-5195/CVE-2016-5195.stap
    dest: /root/CVE-2016-5195.stap
    owner: root
    group: root
    mode: 0600
  when: stap_loaded.rc != 0
    
- name: Install dependencies
  become: true
  become_method: sudo
  shell: "yum install -y --disableexcludes=all --enablerepo=base-debuginfo {{ item }}"
  with_items:
    - systemtap
    - "kernel-debuginfo-{{ ansible_kernel }}"
    - "kernel-devel-{{ ansible_kernel }}"
    
- block:
  - name: Generate the stap module
    become: true
    become_method: sudo
    shell: "stap -p4 -g /root/CVE-2016-5195.stap -m CVE_2016_5195"
    register: stap_mod_gen
    when: stap_loaded.rc != 0

  - name: Load the stap module
    become: true
    become_method: sudo
    shell: "staprun -L {{ item }}"
    with_items: "{{ stap_mod_gen.stdout_lines }}"
    when: stap_loaded.rc != 0
    register: stap_mod_install
    failed_when: stap_mod_install.rc != 0

  rescue:
  - debug:
      msg: "Something is fucked"

  always:
  - name: Remove the stap file
    become: true
    become_method: sudo
    file:
      path: /root/CVE-2016-5195.stap
      state: absent
    tags:
      - cve-cleanup

  - name: Remove the stap module
    become: true
    become_method: sudo
    file:
      path: CVE_2016_5195.ko
      state: absent
